import { NegotiationState, Offer } from "../state.js";
import { generateMesoOptions } from "../../meso.js";
import { ResolvedNegotiationConfig, ExtendedOffer } from "../../types.js";

/**
 * MESOGenerationAgent (Track 3: Adarsh)
 * 
 * @source src/modules/chatbot/engine/meso.ts
 * 
 * Synergy Mandate:
 * - Part 1: Extracts core MESO logic, Pareto calculation, trade-offs
 * - Part 2: Preference-learned option tuning and multi-parameter optimization
 */
export const mesoGenerationNode = async (state: NegotiationState) => {
  if (!state.config || !state.parsedOffer) {
    return {};
  }

  const resolvedConfig = state.config as ResolvedNegotiationConfig;
  
  // Map our generic state.parsedOffer back to the legacy ExtendedOffer shape
  const vendorOffer = {
    total_price: state.parsedOffer.totalPrice,
    payment_terms: state.parsedOffer.paymentTerms,
    payment_terms_days: state.parsedOffer.paymentTermsDays,
    delivery_date: state.parsedOffer.deliveryDate,
    delivery_days: state.parsedOffer.deliveryDays,
    warranty_months: state.parsedOffer.warrantyMonths,
  } as ExtendedOffer;

  // Adapt target utility based on behavioral momentum (Part 2: Multi-parameter optimization)
  let targetUtility = 0.65; // Base utility
  if (state.analysis?.behavior?.momentum === "ACCELERATING") {
    targetUtility = 0.70; // Ask for more if vendor is conceding rapidly
  } else if (state.analysis?.behavior?.concessionVelocity === "STALLED") {
    targetUtility = 0.60; // Lower expectations slightly if we've hit a wall
  }

  const lastAccordoCounterPrice = state.counterOffer?.totalPrice || null;

  // Generate 3 equivalent-utility options
  const result = generateMesoOptions(
    resolvedConfig,
    vendorOffer,
    state.round,
    targetUtility,
    resolvedConfig.currency || "USD",
    lastAccordoCounterPrice
  );

  if (!result.success || result.options.length === 0) {
    return { mesoOptions: [] };
  }

  // Phase 2.2: Integrate with VendorProfilingAgent for personalized options
  // If we know their preference, we can flag it in metadata or sort it first
  let options = result.options;
  if (state.vendorProfile && state.vendorProfile.lastSelectedOfferType) {
    // E.g. re-order or adjust based on profile (in reality we would pass weights to a dynamic MESO generator)
    const pref = state.vendorProfile.lastSelectedOfferType;
    // For now we just pass the options back as generated by the Pareto engine
  }

  // Map MesoResult options back to the State's generic Offer array format
  const mesoOptions: Offer[] = options.map(opt => ({
    totalPrice: opt.offer.total_price || null,
    paymentTerms: opt.offer.payment_terms || null,
    paymentTermsDays: opt.offer.payment_terms_days || null,
    deliveryDays: opt.offer.delivery_days || null,
    warrantyMonths: opt.offer.warranty_months || null,
    customParameters: {
      mesoLabel: opt.label,
      mesoDescription: opt.description,
      mesoTradeoffs: opt.tradeoffs,
      mesoUtility: opt.utility,
      mesoEmphasis: opt.emphasis
    }
  }));

  return { mesoOptions };
};
